# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.17.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
        cache: 'yarn'
    - run: yarn
    - run: yarn build
      id: build
    - run: yarn test
      if: steps.build.outcome == "success"
    - run: yarn bench
      if: steps.build.outcome == "success"
